<?php
/**
 * AdditionalCostType
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.68.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * AdditionalCostType Class Doc Comment
 *
 * @category Class
 * @description Type of additional cost
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdditionalCostType
{
    /**
     * Possible values of this enum
     */
    const SHIPPING = 'SHIPPING';

    const CASH_ON_DELIVERY = 'CASH_ON_DELIVERY';

    const CARD = 'CARD';

    const BANK_TRANSFER = 'BANK_TRANSFER';

    const CASH = 'CASH';

    const PACKING = 'PACKING';

    const DUTY = 'DUTY';

    const OTHER = 'OTHER';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SHIPPING,
            self::CASH_ON_DELIVERY,
            self::CARD,
            self::BANK_TRANSFER,
            self::CASH,
            self::PACKING,
            self::DUTY,
            self::OTHER
        ];
    }
}


