<?php

/**
 * AvailabilityState
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.147.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;

use Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * AvailabilityState Class Doc Comment
 *
 * @category Class
 * @description Represents the availability status of a product.
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AvailabilityState
{
    /**
     * Possible values of this enum
     */
    public const IN_STOCK = 'IN_STOCK';

    public const IN_STOCK_EXTERNAL = 'IN_STOCK_EXTERNAL';

    public const IN_STOCK_EXTERNAL_DELAYED = 'IN_STOCK_EXTERNAL_DELAYED';

    public const LOW_STOCK = 'LOW_STOCK';

    public const OUT_OF_STOCK = 'OUT_OF_STOCK';

    public const ON_DEMAND = 'ON_DEMAND';

    public const RESTOCK_AWAITING = 'RESTOCK_AWAITING';

    public const RESTOCK_SCHEDULED = 'RESTOCK_SCHEDULED';

    public const DISCONTINUED = 'DISCONTINUED';

    public const PENDING_SUPPLIER_CONFIRMATION = 'PENDING_SUPPLIER_CONFIRMATION';

    public const PREORDER = 'PREORDER';

    public const AVAILABLE_ONLINE = 'AVAILABLE_ONLINE';

    public const OTHER = 'OTHER';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::IN_STOCK,
            self::IN_STOCK_EXTERNAL,
            self::IN_STOCK_EXTERNAL_DELAYED,
            self::LOW_STOCK,
            self::OUT_OF_STOCK,
            self::ON_DEMAND,
            self::RESTOCK_AWAITING,
            self::RESTOCK_SCHEDULED,
            self::DISCONTINUED,
            self::PENDING_SUPPLIER_CONFIRMATION,
            self::PREORDER,
            self::AVAILABLE_ONLINE,
            self::OTHER
        ];
    }
}
