<?php
/**
 * Carrier
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Pickup Place Service API
 *
 * Foxdeli API documentation
 *
 * The version of the OpenAPI document: 3.11.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * Carrier Class Doc Comment
 *
 * @category Class
 * @description carrier identifier
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Carrier
{
    /**
     * Possible values of this enum
     */
    public const BUDBEE = 'BUDBEE';

    public const CZECH_POST = 'CZECH_POST';

    public const DHL = 'DHL';

    public const DIY = 'DIY';

    public const DPD = 'DPD';

    public const DPD_CZ = 'DPD_CZ';

    public const DPD_PL = 'DPD_PL';

    public const DPD_SK = 'DPD_SK';

    public const EU_SHIPMENTS = 'EU_SHIPMENTS';

    public const FAN_COURIER = 'FAN_COURIER';

    public const FEDEX = 'FEDEX';

    public const GEBRUDER_WEISS = 'GEBRUDER_WEISS';

    public const GEIS = 'GEIS';

    public const GLS = 'GLS';

    public const GLS_CZ = 'GLS_CZ';

    public const GLS_HR = 'GLS_HR';

    public const GLS_HU = 'GLS_HU';

    public const GLS_RO = 'GLS_RO';

    public const GLS_SI = 'GLS_SI';

    public const GLS_SK = 'GLS_SK';

    public const GO_BALIK = 'GO_BALIK';

    public const INPOST = 'INPOST';

    public const JAPO = 'JAPO';

    public const KURIER_123 = 'KURIER_123';

    public const KURYR_123 = 'KURYR_123';

    public const LANDMARK = 'LANDMARK';

    public const MESSENGER = 'MESSENGER';

    public const PACKETA = 'PACKETA';

    public const PBH = 'PBH';

    public const POST_AG = 'POST_AG';

    public const POCZTA_POLSKA = 'POCZTA_POLSKA';

    public const PPL = 'PPL';

    public const PPL_CPL = 'PPL_CPL';

    public const SAMEDAY = 'SAMEDAY';

    public const SAMEDAY_RO = 'SAMEDAY_RO';

    public const SLOVAKIA_POST = 'SLOVAKIA_POST';

    public const SPEEDY = 'SPEEDY';

    public const SPRING_GDS = 'SPRING_GDS';

    public const SPS = 'SPS';

    public const SWISS_POST = 'SWISS_POST';

    public const TAXYDROMIKI = 'TAXYDROMIKI';

    public const TOP_TRANS = 'TOP_TRANS';

    public const ULOZENKA = 'ULOZENKA';

    public const URGENT_CARGUS = 'URGENT_CARGUS';

    public const UNKNOWN = 'UNKNOWN';

    public const UPS = 'UPS';

    public const WEDO = 'WEDO';

    public const PERSONAL_PICKUP = 'PERSONAL_PICKUP';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BUDBEE,
            self::CZECH_POST,
            self::DHL,
            self::DIY,
            self::DPD,
            self::DPD_CZ,
            self::DPD_PL,
            self::DPD_SK,
            self::EU_SHIPMENTS,
            self::FAN_COURIER,
            self::FEDEX,
            self::GEBRUDER_WEISS,
            self::GEIS,
            self::GLS,
            self::GLS_CZ,
            self::GLS_HR,
            self::GLS_HU,
            self::GLS_RO,
            self::GLS_SI,
            self::GLS_SK,
            self::GO_BALIK,
            self::INPOST,
            self::JAPO,
            self::KURIER_123,
            self::KURYR_123,
            self::LANDMARK,
            self::MESSENGER,
            self::PACKETA,
            self::PBH,
            self::POST_AG,
            self::POCZTA_POLSKA,
            self::PPL,
            self::PPL_CPL,
            self::SAMEDAY,
            self::SAMEDAY_RO,
            self::SLOVAKIA_POST,
            self::SPEEDY,
            self::SPRING_GDS,
            self::SPS,
            self::SWISS_POST,
            self::TAXYDROMIKI,
            self::TOP_TRANS,
            self::ULOZENKA,
            self::URGENT_CARGUS,
            self::UNKNOWN,
            self::UPS,
            self::WEDO,
            self::PERSONAL_PICKUP
        ];
    }
}


