<?php
/**
 * EmailEventType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.90.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * EmailEventType Class Doc Comment
 *
 * @category Class
 * @description type of event for email communication
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailEventType
{
    /**
     * Possible values of this enum
     */
    public const SENT = 'EMAIL_SENT';

    public const PROCESSED = 'EMAIL_PROCESSED';

    public const DROPPED = 'EMAIL_DROPPED';

    public const DELIVERED = 'EMAIL_DELIVERED';

    public const DEFERRED = 'EMAIL_DEFERRED';

    public const BOUNCED = 'EMAIL_BOUNCED';

    public const BLOCKED = 'EMAIL_BLOCKED';

    public const OPENED = 'EMAIL_OPENED';

    public const CLICKED = 'EMAIL_CLICKED';

    public const SPAM_REPORT = 'EMAIL_SPAM_REPORT';

    public const UNSUBSCRIBED = 'EMAIL_UNSUBSCRIBED';

    public const GROUP_UNSUBSCRIBED = 'EMAIL_GROUP_UNSUBSCRIBED';

    public const GROUP_RESUBSCRIBED = 'EMAIL_GROUP_RESUBSCRIBED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SENT,
            self::PROCESSED,
            self::DROPPED,
            self::DELIVERED,
            self::DEFERRED,
            self::BOUNCED,
            self::BLOCKED,
            self::OPENED,
            self::CLICKED,
            self::SPAM_REPORT,
            self::UNSUBSCRIBED,
            self::GROUP_UNSUBSCRIBED,
            self::GROUP_RESUBSCRIBED
        ];
    }
}


