<?php
/**
 * ImportantState
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.68.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * ImportantState Class Doc Comment
 *
 * @category Class
 * @description optional important state assigned to parcel. value is not assigned if parcel is not marked as important
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImportantState
{
    /**
     * Possible values of this enum
     */
    const BAD_RATING = 'BAD_RATING';

    const MALFUNCTION = 'MALFUNCTION';

    const TIME_REASONS = 'TIME_REASONS';

    const ACT_OF_GOD = 'ACT_OF_GOD';

    const CARRIERS_FAULT = 'CARRIERS_FAULT';

    const DAMAGED = 'DAMAGED';

    const NOT_REACHED = 'NOT_REACHED';

    const DISPOSITION_CHANGE = 'DISPOSITION_CHANGE';

    const RETURNING = 'RETURNING';

    const SLIGHTLY_DELAYED = 'SLIGHTLY_DELAYED';

    const NOT_PICKED_1_DAY = 'NOT_PICKED_1DAY';

    const NOT_PICKED_2_DAYS = 'NOT_PICKED_2DAYS';

    const NOT_PICKED_3_DAYS = 'NOT_PICKED_3DAYS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BAD_RATING,
            self::MALFUNCTION,
            self::TIME_REASONS,
            self::ACT_OF_GOD,
            self::CARRIERS_FAULT,
            self::DAMAGED,
            self::NOT_REACHED,
            self::DISPOSITION_CHANGE,
            self::RETURNING,
            self::SLIGHTLY_DELAYED,
            self::NOT_PICKED_1_DAY,
            self::NOT_PICKED_2_DAYS,
            self::NOT_PICKED_3_DAYS
        ];
    }
}


