<?php
/**
 * OrderState
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.78.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * OrderState Class Doc Comment
 *
 * @category Class
 * @description State of order
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderState
{
    /**
     * Possible values of this enum
     */
    public const CREATED = 'CREATED';

    public const PICKING = 'PICKING';

    public const IN_TRANSIT = 'IN_TRANSIT';

    public const PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED';

    public const DELIVERED = 'DELIVERED';

    public const UNDELIVERED = 'UNDELIVERED';

    public const CANCELLED = 'CANCELLED';

    public const RETURNED = 'RETURNED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
            self::PICKING,
            self::IN_TRANSIT,
            self::PARTIALLY_DELIVERED,
            self::DELIVERED,
            self::UNDELIVERED,
            self::CANCELLED,
            self::RETURNED
        ];
    }
}


