<?php
/**
 * PickupPlaceResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Pickup Place Service API
 *
 * Foxdeli API documentation
 *
 * The version of the OpenAPI document: 3.11.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;

use \ArrayAccess;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * PickupPlaceResponse Class Doc Comment
 *
 * @category Class
 * @description Pickup Place
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PickupPlaceResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PickupPlaceResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'eshop_id' => 'string',
        'type' => '\Foxdeli\ApiPhpSdk\Model\DestinationType',
        'carrier' => '\Foxdeli\ApiPhpSdk\Model\Carrier',
        'origin_pickup_place_id' => 'string',
        'origin' => '\Foxdeli\ApiPhpSdk\Model\OriginType',
        'country_code' => '\Foxdeli\ApiPhpSdk\Model\CountryCode',
        'zone_id' => 'string',
        'name' => 'string',
        'location' => '\Foxdeli\ApiPhpSdk\Model\LocationResponse',
        'note' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'image' => 'string',
        'storage_time' => 'int',
        'opening_hours' => '\Foxdeli\ApiPhpSdk\Model\OpeningHoursResponse'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'eshop_id' => 'uuid',
        'type' => null,
        'carrier' => null,
        'origin_pickup_place_id' => null,
        'origin' => null,
        'country_code' => null,
        'zone_id' => null,
        'name' => null,
        'location' => null,
        'note' => null,
        'phone' => null,
        'email' => null,
        'image' => null,
        'storage_time' => 'int32',
        'opening_hours' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static $openAPINullables = [
        'id' => false,
        'eshop_id' => false,
        'type' => false,
        'carrier' => false,
        'origin_pickup_place_id' => false,
        'origin' => false,
        'country_code' => false,
        'zone_id' => false,
        'name' => false,
        'location' => false,
        'note' => false,
        'phone' => false,
        'email' => false,
        'image' => false,
        'storage_time' => false,
        'opening_hours' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var string[]
      */
    protected $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return string[]
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return string[]
     * @phpstan-return array<string, string|null>
     * @psalm-return array<string, string|null>
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return boolean[]
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return string[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'eshop_id' => 'eshopId',
        'type' => 'type',
        'carrier' => 'carrier',
        'origin_pickup_place_id' => 'originPickupPlaceId',
        'origin' => 'origin',
        'country_code' => 'countryCode',
        'zone_id' => 'zoneId',
        'name' => 'name',
        'location' => 'location',
        'note' => 'note',
        'phone' => 'phone',
        'email' => 'email',
        'image' => 'image',
        'storage_time' => 'storageTime',
        'opening_hours' => 'openingHours'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'eshop_id' => 'setEshopId',
        'type' => 'setType',
        'carrier' => 'setCarrier',
        'origin_pickup_place_id' => 'setOriginPickupPlaceId',
        'origin' => 'setOrigin',
        'country_code' => 'setCountryCode',
        'zone_id' => 'setZoneId',
        'name' => 'setName',
        'location' => 'setLocation',
        'note' => 'setNote',
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'image' => 'setImage',
        'storage_time' => 'setStorageTime',
        'opening_hours' => 'setOpeningHours'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'eshop_id' => 'getEshopId',
        'type' => 'getType',
        'carrier' => 'getCarrier',
        'origin_pickup_place_id' => 'getOriginPickupPlaceId',
        'origin' => 'getOrigin',
        'country_code' => 'getCountryCode',
        'zone_id' => 'getZoneId',
        'name' => 'getName',
        'location' => 'getLocation',
        'note' => 'getNote',
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'image' => 'getImage',
        'storage_time' => 'getStorageTime',
        'opening_hours' => 'getOpeningHours'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return string[]
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return string[]
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return string[]
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = [])
    {
        $this->setIfExists('id', $data, null);
        $this->setIfExists('eshop_id', $data, null);
        $this->setIfExists('type', $data, null);
        $this->setIfExists('carrier', $data, null);
        $this->setIfExists('origin_pickup_place_id', $data, null);
        $this->setIfExists('origin', $data, null);
        $this->setIfExists('country_code', $data, null);
        $this->setIfExists('zone_id', $data, null);
        $this->setIfExists('name', $data, null);
        $this->setIfExists('location', $data, null);
        $this->setIfExists('note', $data, null);
        $this->setIfExists('phone', $data, null);
        $this->setIfExists('email', $data, null);
        $this->setIfExists('image', $data, null);
        $this->setIfExists('storage_time', $data, null);
        $this->setIfExists('opening_hours', $data, null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param mixed[]  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['carrier'] === null) {
            $invalidProperties[] = "'carrier' can't be null";
        }
        if ($this->container['origin_pickup_place_id'] === null) {
            $invalidProperties[] = "'origin_pickup_place_id' can't be null";
        }
        if ($this->container['origin'] === null) {
            $invalidProperties[] = "'origin' can't be null";
        }
        if ($this->container['country_code'] === null) {
            $invalidProperties[] = "'country_code' can't be null";
        }
        if ($this->container['zone_id'] === null) {
            $invalidProperties[] = "'zone_id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['location'] === null) {
            $invalidProperties[] = "'location' can't be null";
        }
        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['opening_hours'] === null) {
            $invalidProperties[] = "'opening_hours' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Identifier of pickup place
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets eshop_id
     *
     * @return string|null
     */
    public function getEshopId()
    {
        return $this->container['eshop_id'];
    }

    /**
     * Sets eshop_id
     *
     * @param string|null $eshop_id Id of the eshop this pickup place belongs to
     *
     * @return self
     */
    public function setEshopId($eshop_id)
    {
        if (is_null($eshop_id)) {
            throw new \InvalidArgumentException('non-nullable eshop_id cannot be null');
        }
        $this->container['eshop_id'] = $eshop_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Foxdeli\ApiPhpSdk\Model\DestinationType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|int|\Foxdeli\ApiPhpSdk\Model\DestinationType $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets carrier
     *
     * @return \Foxdeli\ApiPhpSdk\Model\Carrier
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param string|int|\Foxdeli\ApiPhpSdk\Model\Carrier $carrier carrier
     *
     * @return self
     */
    public function setCarrier($carrier)
    {
        if (is_null($carrier)) {
            throw new \InvalidArgumentException('non-nullable carrier cannot be null');
        }
        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets origin_pickup_place_id
     *
     * @return string
     */
    public function getOriginPickupPlaceId()
    {
        return $this->container['origin_pickup_place_id'];
    }

    /**
     * Sets origin_pickup_place_id
     *
     * @param string $origin_pickup_place_id Origin ID of parcelShop/Box
     *
     * @return self
     */
    public function setOriginPickupPlaceId($origin_pickup_place_id)
    {
        if (is_null($origin_pickup_place_id)) {
            throw new \InvalidArgumentException('non-nullable origin_pickup_place_id cannot be null');
        }
        $this->container['origin_pickup_place_id'] = $origin_pickup_place_id;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return \Foxdeli\ApiPhpSdk\Model\OriginType
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param string|int|\Foxdeli\ApiPhpSdk\Model\OriginType $origin origin
     *
     * @return self
     */
    public function setOrigin($origin)
    {
        if (is_null($origin)) {
            throw new \InvalidArgumentException('non-nullable origin cannot be null');
        }
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return \Foxdeli\ApiPhpSdk\Model\CountryCode
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string|int|\Foxdeli\ApiPhpSdk\Model\CountryCode $country_code country_code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets zone_id
     *
     * @return string
     */
    public function getZoneId()
    {
        return $this->container['zone_id'];
    }

    /**
     * Sets zone_id
     *
     * @param string $zone_id zone_id
     *
     * @return self
     */
    public function setZoneId($zone_id)
    {
        if (is_null($zone_id)) {
            throw new \InvalidArgumentException('non-nullable zone_id cannot be null');
        }
        $this->container['zone_id'] = $zone_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \Foxdeli\ApiPhpSdk\Model\LocationResponse
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \Foxdeli\ApiPhpSdk\Model\LocationResponse $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string|null
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string|null $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            throw new \InvalidArgumentException('non-nullable note cannot be null');
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone Customer phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets image
     *
     * @return string|null
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     *
     * @param string|null $image Pickup place image link
     *
     * @return self
     */
    public function setImage($image)
    {
        if (is_null($image)) {
            throw new \InvalidArgumentException('non-nullable image cannot be null');
        }
        $this->container['image'] = $image;

        return $this;
    }

    /**
     * Gets storage_time
     *
     * @return int|null
     */
    public function getStorageTime()
    {
        return $this->container['storage_time'];
    }

    /**
     * Sets storage_time
     *
     * @param int|null $storage_time How long the shipment will be stored, in days
     *
     * @return self
     */
    public function setStorageTime($storage_time)
    {
        if (is_null($storage_time)) {
            throw new \InvalidArgumentException('non-nullable storage_time cannot be null');
        }
        $this->container['storage_time'] = $storage_time;

        return $this;
    }

    /**
     * Gets opening_hours
     *
     * @return \Foxdeli\ApiPhpSdk\Model\OpeningHoursResponse
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param \Foxdeli\ApiPhpSdk\Model\OpeningHoursResponse $opening_hours opening_hours
     *
     * @return self
     */
    public function setOpeningHours($opening_hours)
    {
        if (is_null($opening_hours)) {
            throw new \InvalidArgumentException('non-nullable opening_hours cannot be null');
        }
        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param mixed $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param mixed $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param mixed $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param mixed $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        $string = json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
        if ($string) {
            return $string;
        }
        return "";
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string|false
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


