<?php
/**
 * TimelineType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.113.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;

use Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * TimelineType Class Doc Comment
 *
 * @category Class
 * @description Type of timeline record
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TimelineType
{
    /**
     * Possible values of this enum
     */
    public const NOTE = 'NOTE';

    public const COMMUNICATION = 'COMMUNICATION';

    public const ISSUE_COMMUNICATION = 'ISSUE_COMMUNICATION';

    public const TRACKING = 'TRACKING';

    public const ISSUE_TRACKING = 'ISSUE_TRACKING';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOTE,
            self::COMMUNICATION,
            self::ISSUE_COMMUNICATION,
            self::TRACKING,
            self::ISSUE_TRACKING
        ];
    }
}
