<?php

/**
 * TrackingState
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.140.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Foxdeli\ApiPhpSdk\Model;

use Foxdeli\ApiPhpSdk\ObjectSerializer;

/**
 * TrackingState Class Doc Comment
 *
 * @category Class
 * @description state of parcel tracking
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrackingState
{
    /**
     * Possible values of this enum
     */
    public const AWAITING = 'AWAITING';

    public const SUSPENDED = 'SUSPENDED';

    public const TRACKING = 'TRACKING';

    public const MISSING_CREDENTIALS = 'MISSING_CREDENTIALS';

    public const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

    public const MISSING_CARRIER_CONFIGURATION = 'MISSING_CARRIER_CONFIGURATION';

    public const INACTIVE_CARRIER_CONFIGURATION = 'INACTIVE_CARRIER_CONFIGURATION';

    public const EXPIRED = 'EXPIRED';

    public const CANCELLED = 'CANCELLED';

    public const MISSING_TRACKING_NUMBER = 'MISSING_TRACKING_NUMBER';

    public const INVALID_TRACKING_NUMBER = 'INVALID_TRACKING_NUMBER';

    public const UNKNOWN_TRACKING_NUMBER = 'UNKNOWN_TRACKING_NUMBER';

    public const DONE = 'DONE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AWAITING,
            self::SUSPENDED,
            self::TRACKING,
            self::MISSING_CREDENTIALS,
            self::INVALID_CREDENTIALS,
            self::MISSING_CARRIER_CONFIGURATION,
            self::INACTIVE_CARRIER_CONFIGURATION,
            self::EXPIRED,
            self::CANCELLED,
            self::MISSING_TRACKING_NUMBER,
            self::INVALID_TRACKING_NUMBER,
            self::UNKNOWN_TRACKING_NUMBER,
            self::DONE
        ];
    }
}
