<?php
/**
 * BusinessHoursExceptionTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Pickup Place Service API
 *
 * Foxdeli API documentation
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Foxdeli\ApiPhpSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BusinessHoursExceptionTest Class Doc Comment
 *
 * @category    Class
 * @description BusinessHoursException
 * @package     Foxdeli\ApiPhpSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BusinessHoursExceptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BusinessHoursException"
     */
    public function testBusinessHoursException()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
