<?php
/**
 * ParcelV1ApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Tracking service API
 *
 * Foxdeli API implements JWT tokens as its chosen method of authentication, requiring that these tokens be included in the HTTP header X-API-Key for each request.
 *
 * The version of the OpenAPI document: 14.61.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Foxdeli\ApiPhpSdk\Test\Api;

use \Foxdeli\ApiPhpSdk\Configuration;
use \Foxdeli\ApiPhpSdk\ApiException;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ParcelV1ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ParcelV1ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createParcel
     *
     * Create parcel.
     *
     */
    public function testCreateParcel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteParcel
     *
     * Delete existing parcel.
     *
     */
    public function testDeleteParcel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findParcelById
     *
     * Get existing parcel.
     *
     */
    public function testFindParcelById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateParcel
     *
     * Update existing parcel.
     *
     */
    public function testUpdateParcel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateParcelState
     *
     * Update state of existing parcel.
     *
     */
    public function testUpdateParcelState()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
