<?php
/**
 * PickupPlacePublicControllerApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Foxdeli Pickup Place Service API
 *
 * Foxdeli API documentation
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Foxdeli\ApiPhpSdk\Test\Api;

use \Foxdeli\ApiPhpSdk\Configuration;
use \Foxdeli\ApiPhpSdk\ApiException;
use \Foxdeli\ApiPhpSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PickupPlacePublicControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Foxdeli\ApiPhpSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PickupPlacePublicControllerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getPickupPlace1
     *
     * Get pickup place by Country code, Carrier identifier and Carrier Pickup place ID.
     *
     */
    public function testGetPickupPlace1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPickupPlace2
     *
     * Get pickup place by Foxdeli internal ID.
     *
     */
    public function testGetPickupPlace2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPickupPlaceDeprecated
     *
     * Get pickup place by Country code, Carrier identifier and Carrier Pickup place ID.
     *
     */
    public function testGetPickupPlaceDeprecated()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for loadCarrierPickupPlaces
     *
     * Load pickup places.
     *
     */
    public function testLoadCarrierPickupPlaces()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for loadPickupPlacesByCarrier
     *
     * Load pickup places of given carrier (if available).
     *
     */
    public function testLoadPickupPlacesByCarrier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
